name: Facebook Alerts Cronjob

on:
  schedule:
    - cron: "0 * * * *" # Run every hour
  workflow_dispatch: # Allow manual triggers

jobs:
  facebook-alerts:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Or your project's Node.js version

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Inject environment variables into runtime
      - name: Inject environment variables
        env:
          AUTH_KEY: ${{ secrets.AUTH_KEY }}
          PAGE_ID: ${{ secrets.PAGE_ID }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          LOWER_LATITUDE: ${{ secrets.LOWER_LATITUDE }}
          LOWER_LONGITUDE: ${{ secrets.LOWER_LONGITUDE }}
          UPPER_LATITUDE: ${{ secrets.UPPER_LATITUDE }}
          UPPER_LONGITUDE: ${{ secrets.UPPER_LONGITUDE }}
          FULL_RESPONSE: ${{ secrets.FULL_RESPONSE }}
          LIMIT: ${{ secrets.LIMIT }}
        run: |
          echo "Environment variables injected"

      # Run your Node.js script
      - name: Run Facebook alerts script
        run: node guardianNYC.js
